### ISSUE TITLE
Liquid code

### ISSUE THREAD

**Issue by iooner** [bdesham/inline_highlight#2]
Hi!
It's impossible to add liquid code in {% highlight xxx %}.

**Comment by bdesham** [comment]
I don't understand the issue. Could you please provide a sample piece of code that uses `highlight`, the equivalent sample that uses `ihighlight`, and the output generated by each of these samples?

**Comment by bdesham** [comment]
I don't understand the issue. Could you please provide a sample piece of
code that uses `highlight`, the equivalent sample that uses
`ihighlight`, and the output generated by each of these samples?

**Comment by iooner** [comment]
Example : https://gist.github.com/iooner/b012a0fdae0942431bf3

**Comment by bdesham** [comment]
I still don’t understand. Are you reporting a problem with the inline_highlight plugin or with the built-in highlight tag?

**Comment by iooner** [comment]
Problem with inline_highlight plugin.
Same problem using : {% ihighlight html %}.

**Comment by bdesham** [comment]
ihighlight is supposed to work the same as the built-in highlight. If you've found a bug with both of them then it should be reported as a bug on the Jekyll project, not on this one.
