### ISSUE TITLE
Permission issue causes plugin to not load

### ISSUE THREAD

**Issue by stefanheule** [bdesham/inline_highlight#4]
I tried installing jekyll_inline_highlight using

```
sudo gem install jekyll_inline_highlight
```

However, after I did this, jekyll would no longer work and complain that jekyll_inline_highlight or one of it's dependencies could not be loaded.  After some investigation, it turns out that there was a permission problem with the file `/var/lib/gems/2.3.0/gems/jekyll_inline_highlight-3.0/lib/jekyll_inline_highlight.rb`.  After making readable and executable by everyone, the plugin works.

I'm not 100% sure where the problem lies (maybe I did something wrong?), but this seems like a bug.  Let me know if I can provide more information.

**Comment by bdesham** [comment]
Hi! I don’t believe this is a problem with jekyll_inline_highlight. More likely is that by installing with `sudo`, you’ve inadvertently made the files inaccessible to your own user account. You should try installing the gem without using `sudo`, and if that doesn’t work you may want to look into something like [RVM](http://rvm.io).
