### ISSUE TITLE
Support newer versions of Jekyll

### ISSUE THREAD

**Issue by jjatria** [bdesham/inline_highlight#8]
This gem is currently fixed on 3.0, but the current version of Jekyll is 4.1.1, and it looks like [the changes to support this are fairly minimal](https://github.com/Gizmokid2005/inline_highlight/commit/f748df35e627f1459e707dddf1ac3fe4bd2d8e44).

Please consider releasing a new version.

**Comment by bdesham** [comment]
Thanks for poking me about this! I’ve published version 3.0.1, which is compatible with Jekyll 3 and 4.
